apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-deployment-2-2
  labels:
    app: deployment-2-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-2-2
  template: 
    metadata:
      labels:
        app: deployment-2-2
        service_class: "2"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - available   
      schedulerName: qos-scheduler
      priorityClassName: low-priority
      containers:
      - name: container-2-2
        image: dragnoid99/app:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
