apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-deployment-1-2
  labels:
    app: deployment-1-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-1-2
  template:
    metadata:
      labels:
        app: deployment-1-2
        service_class: "1"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - available    
      schedulerName: qos-scheduler
      priorityClassName: medium-priority
      containers:
      - name: container-1-2
        image: dragnoid99/app:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
