apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-deployment-2-1
  labels:
    app: deployment-2-1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-2-1
  template:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-type
              operator: In
              values:
              - available    
    metadata:
      labels:
        app: deployment-2-1
        service_class: "2"
    spec:
      schedulerName: qos-scheduler
      priorityClassName: low-priority
      containers:
      - name: container-2-1
        image: dragnoid99/app:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
