apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-deployment-0-1
  labels:
    app: deployment-0-1 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: deployment-0-1
  template:
    metadata:
      labels:
        app: deployment-0-1
        service_class: "0"
    spec:
      schedulerName: qos-scheduler
      containers:
      - name: container-0-1
        image: dragnoid99/app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
