apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-deployment-1-1
  labels:
    app: deployment-1-1 
value: 2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-1-1
  template:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-type
              operator: In
              values:
              - available    
    metadata:
      labels:
        app: deployment-1-1
        service_class: "1"
    spec:
      schedulerName: qos-scheduler
      priorityClassName: medium-priority
      containers:
      - name: container-1-1
        image: dragnoid99/app:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
