apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: events-collector-binding
subjects:
  - kind: ServiceAccount
    name: events-collector
    namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-collector
  name: events-collector
spec:
  selector:
    matchLabels:
      app: events-collector
  template:
    metadata:
      labels:
        app: events-collector
    spec:
      serviceAccountName: events-collector
      containers:
      - image: bitnami/kubectl
        name: test
        command: ["kubectl"]
        args: ["get","events", "--watch", "--field-selector", "involvedObject.kind=Pod"]
