apiVersion: v1
kind: Pod
metadata:
  name: qos-scheduler-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values:
            - restricted
  serviceAccountName: serviceaccount
  containers:
  - name: qos-scheduler-container
    image: dragnoid99/qos-scheduler:latest
