apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment-1-2
  labels:
    app: locust-1-2
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: locust-1-2
  template:
    metadata:
      labels:
        app: locust-1-2
    spec:
      containers:
      - name: locust-1-2
        image: dragnoid99/locust-1-2:latest
        ports:
        - containerPort: 8012
