apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment-2-5
  labels:
    app: locust-2-5
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: locust-2-5
  template:
    metadata:
      labels:
        app: locust-2-5
    spec:
      containers:
      - name: locust-2-5
        image: dragnoid99/locust-2-5:latest
        ports:
        - containerPort: 8019
