apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment-2-3
  labels:
    app: locust-2-3
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: locust-2-3
  template:
    metadata:
      labels:
        app: locust-2-3
    spec:
      containers:
      - name: locust-2-3
        image: dragnoid99/locust-2-3:latest
        ports:
        - containerPort: 8017
